name: image_api_client
description: Image Api Client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.2

dev_dependencies:
  build_runner: ^2.6.0
  mocktail: ^1.0.4
  retrofit_generator: ^10.2.1
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  dio: ^5.9.0
  retrofit: ^4.9.2
